version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:nginx
    volumes:
      - wordpress_v:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  mariadb:
    container_name: mariadb
    image:  mariadb:mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb_v:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE} -e 'SELECT 1'
      interval : 1s
      retries: 10
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    image: wordpress:wordpress
    env_file: .env
    volumes:
      - wordpress_v:/var/www/wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
    expose:
      - "9000"
volumes:
  wordpress_v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  mariadb_v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb

networks:
  inception:
    driver: bridge
